version: '3'
services:
  sdaas:
    build: ./sdaas
    ports:
      - "29311:8080"
  api:
    build: ./apis
    ports:
      - "29312:80"
    depends_on:
      - "sdaas"
  lodview:
    image: linkeddatacenter/lodview:1.1.0
    ports:
      - "29319:8080"
    environment:
      - LODVIEW_URISPACE=http://inps.linkeddata.cloud/resource/
      - LODVIEW_URISPACEPREFIX=inps 
      - LODVIEW_SPARQLENDPOINT=https://data.inps.g0v.it/sparql
      - LODVIEW_HOMEURL=https://github.com/g0v-it/data-inps
      - LODVIEW_DATALICENSE=Contiene dati provenienti da INPS.
      - LODMAP_HOME_TITLE=Welcome to INPS g0v knowledge base
      - LODVIEW_PUBLICURLPREFIX=https://data.inps.g0v.it/lodview/
      - LODEVIEW_HEADERLOGO=https://avatars3.githubusercontent.com/u/42692153?s=80
      - "LODVIEW_DATALICENSE=Dati estratti dal portale Open Data di <a href='https://www.inps.it/' target='_blank'><img style='vertical-align: middle' width='48' src='https://www.inps.it/nuovoportaleinps/modelliNuovo/assets/img/logo-inps-pos.png'></a> con licenza <a href='http://www.dati.gov.it/iodl/2.0/' target='_blank'>Italian Open Data License v2.0</a>"
    depends_on:
      - "sdaas"