version: '3'
services:
  sdaas:
    build: ./sdaas
    ports:
      - "29311:8080"
  api:
    build: ./apis
    ports:
      - "29312:80"
    depends_on:
      - "sdaas"
  lodview:
    image: linkeddatacenter/lodview:1.0.2
    ports:
      - "29319:8080"
    environment:
      - LODVIEW_URISPACE=http://inps.linkeddata.cloud/resource/
      - LODVIEW_URISPACEPREFIX=inps 
      - LODVIEW_SPARQLENDPOINT=https://data.inps.g0v.it/sparql
      - LODVIEW_HOMEURL=https://github.com/g0v-it/data-inps
      - LODVIEW_DATALICENSE=Contiene dati provenienti da INPS.
      - LODMAP_HOME_TITLE=Welcome to INPS g0v knowledge base
      - LODVIEW_PUBLICURLPREFIX=https://data.inps.g0v.it/lodview/
    depends_on:
      - "sdaas"